### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by mehmetf** [tekartik/synchronized.dart#11]
Hi @alextekartik 

I see that you already created a branch for null-safety. Thanks for being ahead of the curve! I am interested in bringing that version of the package to Google infra.

- Is the migration still work in progress?
- Are you committed to moving the `master` and `null-safety` branches together until you can merge it back to master? We don't want to fall behind `master`.

**Comment by mehmetf** [comment]
@davidmorgan FYI

**Comment by alextekartik** [comment]
Hi @mehmetf I was actually contacted by google to try the null-safery migration some time ago. See pull request https://github.com/tekartik/synchronized.dart/pull/10 where I had some assistance.

I consider the migration done, unless something has change since nnbd-preview-1. It is a rather small package so it was perfect to start nnbd migration on which I did not read much.

And yes the `null-safety` branch is the latest and `master` has not changed since. And if I make a change in master I will merge to null-safety (if i understand correctly your 2nd question).

It seems that so far nnbd supported package should not be published to `pub.dev` so my plan was to merge back to master when publication is allowed. To be honest I'm not sure I understand what "bringing that version of the package to Google infra" means in terms of what I should do about it.

**Comment by mehmetf** [comment]
> I consider the migration done. 

That's all I needed to hear :).

> It seems that so far nnbd supported package should not be published to pub.dev.

Correct as far as I know even though someone told me today that it is possible to publish "pre-release" packages. David would know more.

> I'm not sure I understand what "bringing that version of the package to Google infra" means in terms of what I should do about it.

That was more FYI. It means we will be starting to use the code in null_safety branch in Google so it is important that the branch does not drift from `master`. It seems this package is quite stable so that's unlikely.

**Comment by mehmetf** [comment]
I will leave this issue open for now. It can be closed when `master` is null safe and null_safety branch is obsolete.

**Comment by davidmorgan** [comment]
Thanks Mehmet!

To clarify on publishing, simplest is to wait for the next dev release of the SDK, plan is for that to have null safety on by default. That should happen in ~weeks. Then all the complications around experiment flags are no longer needed, all that's needed is for the SDK constraint for the null safe version to specify that dev version as the minimum version.
