### ISSUE TITLE
What's the diffenences of  `synchronized` and `await` ?

### ISSUE THREAD

**Issue by wonderful89** [tekartik/synchronized.dart#15]
I read the demo in ReadMe.

then I test the result is the same in two cases.

### case1

```dart
void main(){
    lock.synchronized(write1234);
    lock.synchronized(write1234);
}
```

### case2
```dart
void main() async{
    await write1234();
    await write1234();
}
```

What's the diffenences between the two cases? The dart code run in one Isoluate and it should be in the same thread. I don't know why this dart plugin exists.

**Comment by alextekartik** [comment]
This package prevents concurrent run of a function returning a future until the future completes.

When you control the flow in your application in a single direction, you might won't need this. In a scenario where functions are trigger at any time (like flutter, for example when the user press a button), you don't always control when your function is called. Since the `write1234` function lasts about 4ms, it you don't want 2 calls to happen the same time, await won't be enough.

As an example, rename in your exampe`main` to `doStuff` and run the following:
```dart
Future main() async {
  for (var i = 0; i < 10; i++) {
    void trigger() {
      doStuff();
    }

    // Wait randomly between 2 triggers
    await Future.delayed(Duration(microseconds: Random().nextInt(1000)));
    trigger();
  }
}
```

**case1**
```
# Always
12341234123412341234123412341234123412341234123412341234123412341234123412341234
```
**case2**
```
# Random
11111111212222222132333333324344444443141111111421222222213233333332434444444344
```

There are other ways to solve this, including the [pool](https://pub.dev/packages/pool) package. And in many cases you won't need this package (which technically is not a plugin) until your encounter a concurrent access issue that you want to solve somehow (such as db or network access).
