### ISSUE TITLE
Add a "combined lock" that allows to combine multiple locks into one

### ISSUE THREAD

**Issue by saibotma** [tekartik/synchronized.dart#33]
I just had the requirement to combine multiple locks into one and came up with the following implementation.
What about adding this to the package?

```dart
class CombinedLock implements Lock {
  final Set<Lock> _locks;

  CombinedLock({required Set<Lock> locks}) : _locks = locks;

  @override
  bool get inLock => _locks.every((it) => it.inLock);

  @override
  bool get locked => _locks.every((it) => it.locked);

  @override
  Future<T> synchronized<T>(
    FutureOr<T> Function() computation, {
    Duration? timeout,
  }) async {
    Future<T> runWithLocks(Iterator<Lock> iterator) async {
      if (!iterator.moveNext()) {
        return computation();
      } else {
        final currentLock = iterator.current;
        return currentLock.synchronized(
          () => runWithLocks(iterator),
          timeout: timeout,
        );
      }
    }

    return runWithLocks(_locks.iterator);
  }
}
```

**Comment by alextekartik** [comment]
Very interesting! I'm all in favor. Very smart. Do you have some unit tests you could share? Also do you want to create a PR or want me to integrate your code the way I feel?

**Comment by alextekartik** [comment]
I see that you made some slight modification to make `locks` private (fine for me) so I guess you want me to copy the code. 2 questions remain in my mind:
- Should the API take an iterable (that we'll convert to a set if needed) instead of a set. A duplicated lock will cause a deadlock (unless re-entrant) but that's a developer issue. It is just more common to have an iterable in an API.
- Currently I use `locked` to know if I can grab the lock immediately (for example in a UI login action where I don't want to trigger 2 logins). Here that does not work since if any of the locks is locked, synchronized will wait. Maybe we need another API such as:
```dart
  bool get canLock => !_locks.any((it) => it.locked);
```
But that won't work if an inner lock is also a CombinedLock. Maybe a global `bool get canLock` (or whatever better name) interface could be added:

For simple lock:
```dart
  bool get canLock => !locked;
```
For combined lock
```dart
  bool get canLock => _locks.every((it) => it.canLock);
```

**Comment by saibotma** [comment]
Yeah, using an Iterable is probably better, because then the API does not change in case we use something different from `Set` in the future.

> Currently I use locked to know if I can grab the lock immediately (for example in a UI login action where I don't want to trigger 2 logins). Here that does not work since if any of the locks is locked, synchronized will wait. Maybe we need another API such as:

I think I don't get this yet.
Can you explain it in more detail?

> Do you have some unit tests you could share? Also do you want to create a PR or want me to integrate your code the way I feel?

Didn't have a look at the source code and existing tests yet. I don't mind if you add an adjusted version of my proposal to the package, the way you feel.

Another name suggestion would be `MultiLock`. What do think about this?

Thanks for the great package, btw.

**Comment by alextekartik** [comment]
Ok I added MultiLock in synchronized 3.3.0+1 just published. Thank you!

> I think I don't get this yet.
> Can you explain it in more detail?

I have added some [documentation](https://github.com/tekartik/synchronized.dart/blob/master/synchronized/README.md#lockedinlockcanlock-status)

### canLock

canLock returns whether the lock can be locked immediately.

For basic lock, it is true if the lock is not locked.

For reentrant lock, it is true if the lock is not locked or if the current zone is locked by the lock.

For multi lock, it returns true if all inner locks `canLock` values are true.

**Comment by JulianBissekkou** [comment]
Very cool!

**Comment by saibotma** [comment]
Works like a charm. Thanks a lot!
